name: Purpur Server Start

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  start-server:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository auschecken – nur den minecraft_server-Ordner laden
      - uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1         # nur letzter Commit reicht
          persist-credentials: true
          sparse-checkout: |
            minecraft_server

      # 1b. Force-reset auf neuesten Stand
      - name: Reset to latest
        run: |
          git fetch origin main
          git reset --hard origin/main

      # 2. Java 21 installieren
      - name: Setup Java 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      # 3. RAM prüfen
      - name: Check available RAM
        run: free -h

      # 4. Minecraft Server starten (max 15 GB RAM) + Autosave im Hintergrund
      - name: Start AutoSave & Minecraft Server
        run: |
          echo "[Autosave] Starte Hintergrund-Autosave-Prozess..."
          {
            while true; do
              cd "$GITHUB_WORKSPACE"
              git config user.name "github-actions"
              git config user.email "github-actions@github.com"

              git add -A minecraft_server || true
              git commit -m "Force push Minecraft server data $(date)" >/dev/null 2>&1 || true
              git push origin HEAD:main --force >/dev/null 2>&1 || true

              echo "[Autosave] Repo save done at $(date '+%H:%M:%S')"
              sleep 60
            done
          } &
          AUTOSAVE_PID=$!
          echo "[Autosave] Hintergrundprozess gestartet mit PID $AUTOSAVE_PID"

          cd "$GITHUB_WORKSPACE/minecraft_server"
          java -Xms14G -Xmx14G -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:InitiatingHeapOccupancyPercent=15 -jar purpur.jar nogui

          echo "[Autosave] Serverprozess beendet – beende Autosave-Prozess..."
          kill "$AUTOSAVE_PID" 2>/dev/null || true
          echo "[Autosave] Autosave vollständig gestoppt."

      # 5. Änderungen zurück ins Repo committen und bedingungslos pushen (mit Retry)
      - name: Force-push server data to repo
        run: |
          sleep 10
          cd "$GITHUB_WORKSPACE"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          # eventuelle alte Locks entfernen (Sicherheitsmaßnahme)
          if [ -f ".git/index.lock" ]; then
            echo "[Autosave] Alte index.lock gefunden – lösche..."
            rm -f .git/index.lock
          fi

          git add -A minecraft_server
          git commit -m "Auto-save Minecraft server data" || echo "No changes to commit"

          # Push versuchen, bis er erfolgreich ist
          while true; do
            echo "[Autosave] Versuche, Änderungen zu pushen..."
            if git push origin HEAD:main --force; then
              echo "[Autosave] Push erfolgreich!"
              break
            else
              echo "[Autosave] Push fehlgeschlagen, warte 10 Sekunden und versuche erneut..."
              sleep 10
            fi
          done
