name: Purpur Server Start - Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  locate-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Lookup GeoIP
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "Runner IP: $IP"
          curl -s "https://ipinfo.io/$IP"
  locate-runner2:
    runs-on: ubuntu-latest
    steps:
      - name: Lookup GeoIP
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "Runner IP: $IP"
          curl -s "https://ipinfo.io/$IP"
  locate-runner3:
    runs-on: ubuntu-latest
    steps:
      - name: Lookup GeoIP
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "Runner IP: $IP"
          curl -s "https://ipinfo.io/$IP"
  locate-runner4:
    runs-on: ubuntu-latest
    steps:
      - name: Lookup GeoIP
        run: |
          IP=$(curl -s https://api.ipify.org)
          echo "Runner IP: $IP"
          curl -s "https://ipinfo.io/$IP"
